networks:
  httpsvc:
    name: httpsvc
    external: true
services:
  httpmux:
    container_name: httpmux
    image: caddy:2.7.4-alpine
    networks:
      - httpsvc
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - type: bind
        source: Caddyfile
        target: /etc/caddy/Caddyfile
      - httpmux_config:/config
      - httpmux_data:/data
volumes:
  httpmux_config:
  httpmux_data:
    external: true
